# -*- coding: utf-8 -*-
"""Copy of pt1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6eOIDPMhjTOr5RcS4bRYWdBjdwiLFTD
"""

#21) which no is greater no in 3 numbers.
x=int(input("enter 1st no."))
y=int(input("enter 2nd no."))
z=int(input("enter 3rd no."))
if x>y>z:
  print("1st no. is greater")
elif y>x>z:
  print("2nd no. is greater")
else:
  print("3rd no. is greater")

#22program to check whether a number is divisible by 5 and 11 or not.
num=int(input("enter a +ve no."))
if ((num%5==0)and(num%11==0)):
  print("given no. is divisible by 5 & 11")
else:
  print("given no. not divisible by 5 & 11")

#23) program to display Digit in text (0 to 9).
num=int(input("enter a no. between 0 to 9:"))
if (num==0):
  print("Zero")
elif (num==1):
  print("One")
elif(num==2):
  print("two")
elif(num==3):
  print("three")
elif(num==4):
  print("four")
elif(num==5):
  print("five")
elif(num==6):
  print("six")
elif(num==7):
  print("seven")
elif(num==8):
  print("eight")
elif(num==9):
  print("nine")
else:
  print("no text available")

#24) program to Check given character is vowel or not.
ch=input("enter a character:")
if(ch=='a'or ch=='e'or ch=='i'or ch=='o'or ch=='u'):
  print("character is a vowel")
else:
  print("Character is not a vowel")

#25) program to print roots of a quadratic equation ax 2 + bx +c=0 (where a≠0).
import math
a = 1
b = 5
c = 6
d = (b**2) - (4*a*c)
sol1 = (-b-math.sqrt(d))/(2*a)
sol2 = (-b+math.sqrt(d))/(2*a)
print('The solution are {0} and {1}'.format(sol1,sol2))

#26program to check whether the year is leap year or not.
year = 2003
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
else:
    print("{0} is not a leap year".format(year))

#27)program to input marks in 3 subjects, compute average and then calculate grades.
mark1=int(input("enter the mark for subject 1:"))
mark2=int(input("enter the mark for subject 2:"))
mark3=int(input("enter the mark for subject 3:"))
print("average mark is:",(mark1+mark2+mark3)/3)
per=((mark1+mark2+mark3)/300)*110
print("percentage",per)
if per >=80:
  print("Grade is 'A")
elif per >= 70 and per <= 79 :
    print ("Grade is 'B'")
elif per >= 60 and per <= 69 :
    print ("Grade is 'C'")
elif per >= 50 and per <= 59 :
    print ("Grade is 'D'")
elif per >= 40 and per <= 49 :
    print ("Grade is 'E'")
elif per <= 39 :
    print ("Grade is 'R'")

#28Write a menu driven program to calculate:
def circle():

   print("You choose Circle...")

   radius=int(input("enter the radius : "))

   print("Area of the circle with the radius of ",radius," units is", 3.14* (radius**2),"square units.")

def square():

   print("You choose Square...")

   side=int(input("enter the size of a side of a square : "))

   print("Area of the square with the a side of ",side," units is",side**2,"square units.")


def rectangle():

   print("You choose Rectangle...")

   length=int(input("enter the length of the rectangle : "))

   breadth=int(input("enter the breadth of the rectangle : "))

   print("Area of the rectangle with length and breadth ",length, " ",breadth," units is",length*breadth,"square units.")

"""ITERATIVE STATEMENTS::"""

#29)Write a program to display all number from 1 to 15.
for i in range(1,16):
  print(i)

#30) program to display sum of all numbers from 1 to 10.
n=int(input("Enter the total number you want to enter:"))

sum=0

for i in range(n):

    x=int(input("Enter the number:"))

    sum=sum+x

avg=sum/n

print("Average=",avg)

#31) program to display Average of number
n=int(input("Enter the total number you want to enter:"))
sum=0
for i in range(n):
    x=int(input("Enter the number:"))
    sum=sum+x
avg=sum/n

print("Average=",avg)

#32) program to display multiply all numbers from 1 to 10.
num=int(input("enter the number"))
for count in range(1,11):
  print(num*count)

#33) program to display Square all numbers from 1 to 20.
def printValues():
	l = list()
	for i in range(1,21):
		l.append(i**2)
	print(l)
printValues()

#34)program to display all odd numbers from 1 to 100
start, end = 1,100
for num in range(start, end + 1):
    if num % 2 != 0:
        print(num, end = " ")

#35)Write a program to display all even numbers from 1 to 100.
start, end = 1, 100
for num in range(start, end + 1):
    if num % 2 == 0:
        print(num, end = " ")

#36program that uses exactly four for loops to print the sequence of AAAAAAAAAABBBBBBBCCCCCCEEEEE
for i in range (1, 5) :
    print ("A" * i , end = "")
for i in range (3, 5) :
    print ("B" * i , end = "")
for i in range (1, 4) :
    print ("C" * i , end = "")
for i in range (2, 4) :
    print ("E" * i , end = "")

#37Print first 10 prime numbers.
lowervalue = 1
uppervalue=10
print("the prime no. in the rage are:")
for number in range (lowervalue, uppervalue+1):
  if number>1:
    for i in range(2,number):
      if (number%i)==0:
        break
    else:
      print(number)

#38Write a program to print the following *, **...
n = int(input("Enter the number of rows"))  
for i in range(0, n):   
        for j in range(0, i + 1):   
            print("* ", end="")         
        print()

#39)program to print following pattern#,##...
rows = 5
for i in range(rows, 0, -1):
    for j in range(0, i + 1):
        print('#', end=' ')
    print("\r")

#40Write a script to print following:8,86..
num = "8642"
for i in range (4) :
    print (num[ : i + 1])

#41Print N Fibonacci numbers.
num = int (input ("Enter the number :"))
a = 0
b = 1
c = 0
print (0, end = " ")
while 0 < num :
    a, b = b, c
    c = b + a
    num -= 1
    print (c, end = " ")

